version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      #FLASK_ENV: production
      FLASK_APP: run.py
      FLASK_DB_TYPE: postgres
      FLASK_DB_USER: postgres
      FLASK_DB_NAME: postgres
      FLASK_DB_PASSWORD: secretpass
      FLASK_DB_HOST: db
      FLASK_DB_PORT: 5432
    depends_on:
      - db
    networks:
      - appnet
    expose:
      - "5000"
    ports:
      - "5000:5000"
    # deploy:
    #   replicas: 1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:5000
    restart: always

    networks:
      - appnet
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge